apiVersion: v2
name: reversed-ip
description: A Helm chart to deploy reversed-ip Node.js app and MySQL.
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: "12.0.0"
    repository: "https://charts.bitnami.com/bitnami"