apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reversed-ip.fullname" . }}
  labels:
    app: {{ include "reversed-ip.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "reversed-ip.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "reversed-ip.name" . }}
    spec:
      initContainers:
      - name: wait-for-mysql
        image: bitnami/mysql:latest
        envFrom:
        - secretRef:
            name: {{ include "reversed-ip.fullname" . }}
        command:
        - sh
        - -c
        - |
          echo "Waiting for MySQL to be ready..."
          until mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" -e "SELECT 1"; do
            echo "MySQL is not ready yet. Retrying..."
            sleep 2
          done
          echo "MySQL is ready."
      containers:
      - name: reversed-ip
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.port }}
        envFrom:
        - secretRef:
            name: {{ include "reversed-ip.fullname" . }}