
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reversed-ip.fullname" . }}
  labels:
    app: {{ include "reversed-ip.name" . }}
type: Opaque
data:
  DB_HOST: {{ printf "%s.%s.svc.cluster.local" (include "reversed-ip.mysql.serviceName" .) .Release.Namespace | b64enc | quote }}
  DB_USER: {{ .Values.mysql.auth.username | default "reversed_user" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.auth.password | default "Passw0rd!" | b64enc | quote }}
  DB_NAME: {{ .Values.mysql.auth.database | default "reversed_ip_db" | b64enc | quote }}