apiVersion: v1
kind: Service
metadata:
  name: {{ include "reversed-ip.fullname" . }}
  labels:
    app: {{ include "reversed-ip.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "reversed-ip.name" . }}
