apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: {{ .Values.externalSecret.dataFrom.conversionStrategy }}
        decodingStrategy: {{ .Values.externalSecret.dataFrom.decodingStrategy }}
        key: {{ .Values.externalSecret.dataFrom.key }}
        metadataPolicy: {{ .Values.externalSecret.dataFrom.metadataPolicy }}
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreRef }}
  target:
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
    name: {{ .Release.Name }}