# Node.js app config
local:
  enabled: false
image:
  repository: reversed-ip
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

app:
  port: 3000

## ExternalSecret
externalSecret:
  dataFrom:
    key: reversed-ip
    conversionStrategy: Default
    decodingStrategy: None
    metadataPolicy: None
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRef: reversed-ip-secret-store


# Horizontal Pod Autoscaler
hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuTargetUtilization: 80
  memoryTargetUtilization: 70

# Pod Disruption Budget

pdb:
  minAvailable: 1